export const bannedWallets = [
  "GCMDVONMCUMSU55WDUNUPJN7UMYDJFL2HBTQGAO7TUUUBARIPFBAPCN7",
  "GDG4OCQ5C4IVUTU2WXNCVBMLK7VOF3HOA54FEKQQJZYMMSNBPELKQ7OZ",
  "GDOQVIBYMAA3OBC4AYRPYITZWCSZUTC4NETXLTDUOPBGRZRQADGD5WUY",
];
